/**
* @license
* Copyright 2020 Dynatrace LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
 */

package sharing

import (
	"github.com/dynatrace-oss/terraform-provider-dynatrace/terraform/hcl"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// AnonymousAccess represents configuration of the [anonymous access](https://dt-url.net/ov03sf1) to the dashboard
type AnonymousAccess struct {
	ManagementZoneIDs []string `json:"managementZoneIds"` // A list of management zones that can display data on the publicly shared dashboard. \n\nSpecify management zone IDs here. For each management zone you specify Dynatrace generates an access link. You can access them in the **urls** list. \n\nTo share the dashboard with its default management zone, use the `default` value
	// READ ONLY
	URLs map[string]string `json:"urls,omitempty"` // A list of URLs for anonymous access to the dashboard. \n\nEach link grants access to data from the specific management zone, listed in the in the **managementZoneIds** list. \n\nThese links are automatically generated by Dynatrace, you can't change them
}

func (me *AnonymousAccess) IsEmpty() bool {
	return len(me.ManagementZoneIDs) == 0 && len(me.URLs) == 0
}

func (me *AnonymousAccess) Schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"management_zones": {
			Type:        schema.TypeSet,
			Elem:        &schema.Schema{Type: schema.TypeString},
			Required:    true,
			MinItems:    1,
			Description: "A list of management zones that can display data on the publicly shared dashboard. \n\nSpecify management zone IDs here. For each management zone you specify Dynatrace generates an access link. To share the dashboard with its default management zone, use the `default` value",
		},
	}
}

func (me *AnonymousAccess) MarshalHCL(properties hcl.Properties) error {
	return properties.Encode("management_zones", me.ManagementZoneIDs)
}

func (me *AnonymousAccess) UnmarshalHCL(decoder hcl.Decoder) error {
	return decoder.Decode("management_zones", &me.ManagementZoneIDs)
}
