---
layout: ""
page_title: "dynatrace_ddu_pool Resource - terraform-provider-dynatrace"
description: |-
  The resource `dynatrace_ddu_pool` covers configuration for Davis Data Unit Pools
---

# dynatrace_ddu_pool (Resource)


## Dynatrace Documentation

- DDU Pools - https://www.dynatrace.com/support/help/monitoring-consumption/davis-data-units#ddu-pools

- Settings API - https://www.dynatrace.com/support/help/dynatrace-api/environment-api/settings (schemaId: `builtin:accounting.ddu.limit`)

## Resource Example Usage

```terraform
resource "dynatrace_ddu_pool" "#name#" {
  metrics {
    enabled = true
    type    = "MONTHLY"
    value   = 123
  }
  log_monitoring {
    enabled = true
    type    = "MONTHLY"
    value   = 124
  }
  events {
    enabled = true
    type    = "MONTHLY"
    value   = 125
  }
  serverless {
    enabled = true
    type    = "MONTHLY"
    value   = 126
  }
  traces {
    enabled = true
    type    = "MONTHLY"
    value   = 127
  }
}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Optional

- `events` (Block List, Max: 1) DDU pool settings for Events (see [below for nested schema](#nestedblock--events))
- `log_monitoring` (Block List, Max: 1) DDU pool settings for Log Monitoring (see [below for nested schema](#nestedblock--log_monitoring))
- `metrics` (Block List, Max: 1) DDU pool settings for Metrics (see [below for nested schema](#nestedblock--metrics))
- `serverless` (Block List, Max: 1) DDU pool settings for Serverless (see [below for nested schema](#nestedblock--serverless))
- `traces` (Block List, Max: 1) DDU pool settings for Traces (see [below for nested schema](#nestedblock--traces))

### Read-Only

- `id` (String) The ID of this resource.

<a id="nestedblock--events"></a>
### Nested Schema for `events`

Required:

- `enabled` (Boolean) Is the limit configuration enabled

Optional:

- `type` (String) Type of the limit applied: MONTHLY or ANNUAL
- `value` (Number) Value of the DDU limit applied for provided timerange


<a id="nestedblock--log_monitoring"></a>
### Nested Schema for `log_monitoring`

Required:

- `enabled` (Boolean) Is the limit configuration enabled

Optional:

- `type` (String) Type of the limit applied: MONTHLY or ANNUAL
- `value` (Number) Value of the DDU limit applied for provided timerange


<a id="nestedblock--metrics"></a>
### Nested Schema for `metrics`

Required:

- `enabled` (Boolean) Is the limit configuration enabled

Optional:

- `type` (String) Type of the limit applied: MONTHLY or ANNUAL
- `value` (Number) Value of the DDU limit applied for provided timerange


<a id="nestedblock--serverless"></a>
### Nested Schema for `serverless`

Required:

- `enabled` (Boolean) Is the limit configuration enabled

Optional:

- `type` (String) Type of the limit applied: MONTHLY or ANNUAL
- `value` (Number) Value of the DDU limit applied for provided timerange


<a id="nestedblock--traces"></a>
### Nested Schema for `traces`

Required:

- `enabled` (Boolean) Is the limit configuration enabled

Optional:

- `type` (String) Type of the limit applied: MONTHLY or ANNUAL
- `value` (Number) Value of the DDU limit applied for provided timerange