name: Test WIF Auth
on:
  push:
    branches:
      - feat/gcp-wif
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: 'projects/${{ secrets.DT_GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: '${{ secrets.DT_GCP_SERVICE_ACCOUNT }}'

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1

      - name: Verify identity
        run: gcloud auth list

      - name: Smoke test API access
        run: gcloud storage buckets list --limit=5
